# -*- coding: utf-8 -*-
# @Author: Hu Wei
# @Email: hustwei@qq.com
# @DateTime: 2017-12-07 20:37:47
# @Last Modified by: Huwei
# @Last Modified time: 2017-12-11 18:56:37

# Form implementation generated from reading ui file '.\MplMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 552)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(16, 29, 711, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.temTab = QtWidgets.QWidget()
        self.temTab.setObjectName("temTab")
        self.temwidget = MplCanvasWrapper(self.temTab)
        self.temwidget.setGeometry(QtCore.QRect(10, 30, 691, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temwidget.sizePolicy().hasHeightForWidth())
        self.temwidget.setSizePolicy(sizePolicy)
        self.temwidget.setObjectName("temwidget")
        self.temStartBtn = QtWidgets.QPushButton(self.temTab)
        self.temStartBtn.setGeometry(QtCore.QRect(10, 0, 75, 23))
        self.temStartBtn.setObjectName("temStartBtn")
        self.temPauseBtn = QtWidgets.QPushButton(self.temTab)
        self.temPauseBtn.setGeometry(QtCore.QRect(80, 0, 75, 23))
        self.temPauseBtn.setObjectName("temPauseBtn")
        self.tabWidget.addTab(self.temTab, "")
        self.humTab = QtWidgets.QWidget()
        self.humTab.setObjectName("humTab")
        self.humwidget = MplCanvasWrapper(self.humTab)
        self.humwidget.setGeometry(QtCore.QRect(10, 30, 691, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humwidget.sizePolicy().hasHeightForWidth())
        self.humwidget.setSizePolicy(sizePolicy)
        self.humwidget.setObjectName("humwidget")
        self.humStartBtn = QtWidgets.QPushButton(self.humTab)
        self.humStartBtn.setGeometry(QtCore.QRect(10, 0, 75, 23))
        self.humStartBtn.setObjectName("humStartBtn")
        self.humPauseBtn = QtWidgets.QPushButton(self.humTab)
        self.humPauseBtn.setGeometry(QtCore.QRect(80, 0, 75, 23))
        self.humPauseBtn.setObjectName("humPauseBtn")
        self.tabWidget.addTab(self.humTab, "")
        self.preTab = QtWidgets.QWidget()
        self.preTab.setObjectName("preTab")
        self.prewidget = MplCanvasWrapper(self.preTab)
        self.prewidget.setGeometry(QtCore.QRect(10, 30, 691, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prewidget.sizePolicy().hasHeightForWidth())
        self.prewidget.setSizePolicy(sizePolicy)
        self.prewidget.setObjectName("prewidget")
        self.prePauseBtn = QtWidgets.QPushButton(self.preTab)
        self.prePauseBtn.setGeometry(QtCore.QRect(80, 0, 75, 23))
        self.prePauseBtn.setObjectName("prePauseBtn")
        self.preStartBtn = QtWidgets.QPushButton(self.preTab)
        self.preStartBtn.setGeometry(QtCore.QRect(10, 0, 75, 23))
        self.preStartBtn.setObjectName("preStartBtn")
        self.tabWidget.addTab(self.preTab, "")
        self.LEDTab = QtWidgets.QWidget()
        self.LEDTab.setObjectName("LEDTab")
        self.tabWidget.addTab(self.LEDTab, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 0, 701, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.timeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout.addWidget(self.timeLabel)
        self.horizontalLayoutWidget.raise_()
        self.tabWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 742, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IOT-Huwei"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.temStartBtn.setText(_translate("MainWindow", "Start"))
        self.temPauseBtn.setText(_translate("MainWindow", "Pause"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.temTab), _translate("MainWindow", "Temperature"))
        self.humStartBtn.setText(_translate("MainWindow", "Start"))
        self.humPauseBtn.setText(_translate("MainWindow", "Pause"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.humTab), _translate("MainWindow", "Humidity"))
        self.prePauseBtn.setText(_translate("MainWindow", "Pause"))
        self.preStartBtn.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preTab), _translate("MainWindow", "Pressure"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LEDTab), _translate("MainWindow", "LED"))
        self.timeLabel.setText(_translate("MainWindow", "Time"))

from mplCanvasWrapper import MplCanvasWrapper
